config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  

  Photogur::Application.routes.draw do
    resources :photos

    root 'welcome#index'
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)

    if @photo.save 
    redirect_to @photo
  else 
    render 'new'
  end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def index
    @photos = Photo.all
  end

  def update
    @photo = Photo.find(params[:id])

    if @photo.update(photo_params)
        redirect_to @photo
    else 
      render 'edit'
    end
  end

  def edit 
    @photo = Photo.find(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_path
  end

  private
    def photo_params
      params.require(:photo).permit(:title, :author, :url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @photos = Photo.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Front Page</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">photoGur</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="hover"><a href="/photos/new">Add New Photo</a></li>
      <li class="hover"><a href="/photos">Show All Photos</a></li>
    </ul>
  </section>
  </nav> 
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo do |p| %>
 
  <p>
    <%= p.label :title %><br>
    <%= p.text_field :title %>
  </p>
 
  <p>
    <%= p.label :author %><br>
    <%= p.text_field :author %>
  </p>
  
  <p>
  <%= p.label :url %><br>
  <%= p.text_field :url %>
  </p>
 
  <p>
    <%= p.submit %>
  </p>
<% end %>

app/views/photos/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Edit</title>
</head>
<body>
 <h1> Edit Photo </h1>
 <%= render 'form' %>
 <%= link_to 'Back', photo_path %>
</div>
</body>
</html>

app/views/photos/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Index</title>
</head>
<body>
  <h1> Listing Photos </h1>
  <table>
    <tr>
    <th> Title </th>
    <th> Author </th>
    </tr>
  <% @photos.each do |photo| %>
    <tr>
      <td> <%= photo.title %></td>
      <td> <%= photo.author %></td>
      <td> <%= photo.url %> </td>
      <td> <%= link_to 'Show', photo_path(photo) %></td>
      <td> <%= link_to 'Edit', edit_photo_path(photo) %></td>
      <td><%= link_to 'Delete', photo_path(photo),
                    method: :delete, data: { confirm: 'Are you sure?'} %></tr>
  <% end %>
  </table>
</body>
</html>

app/views/photos/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Add New Photo</title>
</head>
<body>
  <h1> Add New Photo </h1>
  <%= render 'form' %>
  
  <%= link_to 'Back', photos_path %>
  
</body>
</html>

app/views/photos/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Show All</title>
</head>
<body>
      
      
      <p>
        <strong> Title: </strong>
        <%= @photo.title %>
      </p>

      <p>
      <strong> Author: </strong>
      <%= @photo.author %>
      </p>

      <p>
      <em> Url: </em>
      <img src="<%= @photo.url %>" alt="">
      </p>
  
      
      <%= link_to 'Edit', edit_photo_path(@photo)%>


</body>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>photoGur</title>
</head>
<body>
  <div class="row" >
    <div class="small-9 large-9 columns">
      <div class =  "row">
        
      
          <% @photos.shuffle.each do |photo| %> 
          <div style = "padding: 20px 20px 20px 20px;" class="small-3 large-3 column">
            <a href="photos/<%= photo.id%>"><img src= "<%= photo.url %>" /></a>
          </div>
            <% end %>
        
      </div> 

  </div>
  <div style = "padding-top: 20px; " class = "small-3 large-3 columns">
    <img src="http://placehold.it/200x1000" alt="">

  </div> 
  </div>
</body>
</html>